### PR TITLE
Issue #3078608: Github Guardr Project: Require Guardr and Guardr Core…

### PR DESCRIPTION
**Pull request by shrop**
… beta versions

### CODE REVIEW

**Comment by joestewart** [comment]
Build error due to -

drupal-composer/drupal-project issue: https://github.com/drupal-composer/drupal-project/issues/511
Drupal core issue: https://www.drupal.org/project/drupal/issues/3078671

**Comment by joestewart** [comment]
Approve of the change.

**Comment by shrop** [comment]
Thanks for the heads up on this issue, @joestewart!

**Review by joestewart — APPROVED** [review]
Approved after tests pass.

Started tests again since the problem is corrected - https://packagist.org/packages/behat/mink-selenium2-driver#1.3.x-dev

**Pull request merged**
